### ISSUE TITLE
Incorrect install link

### ISSUE THREAD

**Issue by arun-gupta** [couchbase-guides/java-sdk#2]
The link to install and setup Couchbase is:

http://developer.couchbase.com/documentation/server/current/install/install-intro.html

This is redirected to:

http://developer.couchbase.com/documentation/server/current/install/plan-for-production.html

The correct link should be:

http://developer.couchbase.com/documentation/server/current/getting-started/installing.html

**Comment by ldoguin** [comment]
resolved
