### ISSUE TITLE
Update .gitignore file to include user-specific files

### ISSUE THREAD

**Issue by arun-gupta** [couchbase-guides/java-sdk#3]
Do `gradlew` and `gradlew.bat` scripts need to be bundled?

Ditto with `.settings` directory in both `initial` and `complete`.

What about `initial/gradle/wrapper` directory?

**Comment by ldoguin** [comment]
gradlew, gradlew.batt and wrapper are here to avoid installing gradle system wide. We need to remove .settings indeed.
